platform :ios, "8.0"

target 'YInkeLiveDemo' do
#use_framework!
pod 'AFNetworking', '~>3.1.0'
pod 'SDWebImage’, '~>3.8.0'
pod 'YYCache', '~>1.0.0'
pod 'YYModel', '~>1.0.0'
pod 'YYCategories', '~>1.0.0'
pod 'CocoaLumberjack', '~>2.3.0'
pod 'MJRefresh', '~>3.1.10'
pod 'MBProgressHUD', '~>1.0.0'


end
